### ISSUE TITLE
Update maintainer names

### ISSUE THREAD

**Issue by abishekvashok** [sdrausty/sdrausty.github.io#1]
Please update the maintainer names on  `/pages/more.md` and other files.

For example, see cmatrix which is maintained by me:
```
54 Package: cmatrix
Maintainer: Fredrik Fornwall @fornwall
Description: Command producing a Matrix-style animation
Homepage: https://github.com/abishekvashok/cmatrix
```

Please don't put wron maintainer names, I see that all packages have a maintainer
with the name `Fredrik Fornwall @fornwall`. Would be better if you update it.

**Comment by SDRausty** [comment]
@abishekvashok Thank you for your time and post. https://sdrausty.github.io/pages/more is automatically generated via a script and crond once a day in Termux, and then uploaded to GitHub. 

http://termux.net/dists/stable/main/binary-all/Packages.xz and http://termux.net/dists/stable/main/binary-arm/Packages.xz are sources for this page. That is where all information for the automatically generated file more.md is stored. So you should address this issue upstream, since Packages.xz is where maintainer info is stored. 

If the information on more.md is incorrect, then the information from the corresponding Packages.xz must be incorrect too. From your post it appears this information is incorrect in Packages.xz Please address this issue upstream in https://github.com/termux/termux-packages or in the Termux package, in this case cmatrix itself.

**Comment by SDRausty** [comment]
@abishekvashok add TERMUX_PKG_MAINTAINER to your https://github.com/termux/termux-packages/blob/master/packages/cmatrix/build.sh file. This should propagate the correct maintainer information to https://sdrausty.github.io/pages/more 

Please see https://github.com/termux/termux-packages/blob/master/packages/bs1770gain/build.sh for example how to propagate package maintainer info correctly in Termux Packages. 

If this doesn't help, please feel free to reopen this issue.

**Comment by abishekvashok** [comment]
Thanks @sdrausty. Would be better if you document it in the Readme.md for future contributors :)
